#!/usr/bin/env node

/**
 * Development setup script for Gmail Pub/Sub Worker
 * This script helps with local development and testing
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

function execCommand(command, description) {
  console.log(`\n🔄 ${description}...`);
  try {
    const output = execSync(command, { encoding: 'utf8', stdio: 'pipe' });
    console.log(`✅ ${description} completed`);
    return output;
  } catch (error) {
    console.error(`❌ ${description} failed:`, error.message);
    throw error;
  }
}

function createEnvFile(config) {
  const envContent = `# Gmail Pub/Sub Worker Environment Variables
# Generated by dev-setup.js

# Google Cloud Configuration
GOOGLE_CLOUD_PROJECT_ID="${config.projectId}"
PORT=8080

# Google OAuth Credentials
GOOGLE_CLIENT_ID="${config.googleClientId}"
GOOGLE_CLIENT_SECRET="${config.googleClientSecret}"
NEXTAUTH_URL="${config.nextAuthUrl}"

# Supabase Configuration
SUPABASE_URL="${config.supabaseUrl}"
SUPABASE_SERVICE_ROLE_KEY="${config.supabaseKey}"

# Encryption Key (32 characters)
ENCRYPTION_KEY="${config.encryptionKey}"

# Development Mode
NODE_ENV=development
`;

  fs.writeFileSync('.env', envContent);
  console.log('✅ Created .env file');
}

function generateEncryptionKey() {
  const crypto = require('crypto');
  return crypto.randomBytes(32).toString('hex');
}

function validateConfig(config) {
  const required = [
    'projectId',
    'googleClientId', 
    'googleClientSecret',
    'nextAuthUrl',
    'supabaseUrl',
    'supabaseKey'
  ];

  for (const field of required) {
    if (!config[field]) {
      throw new Error(`Missing required field: ${field}`);
    }
  }

  // Validate URLs
  try {
    new URL(config.nextAuthUrl);
    new URL(config.supabaseUrl);
  } catch (error) {
    throw new Error('Invalid URL format');
  }

  // Validate encryption key length
  if (config.encryptionKey.length !== 64) {
    throw new Error('Encryption key must be 64 characters (32 bytes hex)');
  }
}

function createTestMessage(userEmail, historyId = '12345') {
  const message = {
    emailAddress: userEmail,
    historyId: historyId
  };
  
  const encoded = Buffer.from(JSON.stringify(message)).toString('base64');
  
  return {
    message: {
      data: encoded,
      messageId: `test-${Date.now()}`,
      publishTime: new Date().toISOString()
    }
  };
}

function createDockerComposeFile() {
  const dockerCompose = `version: '3.8'

services:
  gmail-worker:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped

  # Optional: Local Pub/Sub emulator for testing
  pubsub-emulator:
    image: google/cloud-sdk:alpine
    ports:
      - "8085:8085"
    command: >
      sh -c "gcloud beta emulators pubsub start
             --project=test-project
             --host-port=0.0.0.0:8085"
    environment:
      - PUBSUB_EMULATOR_HOST=localhost:8085
`;

  fs.writeFileSync('docker-compose.yml', dockerCompose);
  console.log('✅ Created docker-compose.yml');
}

function createTestScript() {
  const testScript = `#!/usr/bin/env node

/**
 * Test script for Gmail Pub/Sub Worker
 * Sends test Pub/Sub messages to the local server
 */

const axios = require('axios');

const SERVER_URL = process.env.SERVER_URL || 'http://localhost:8080';

function createTestMessage(userEmail, historyId = '12345') {
  const message = {
    emailAddress: userEmail,
    historyId: historyId
  };
  
  const encoded = Buffer.from(JSON.stringify(message)).toString('base64');
  
  return {
    message: {
      data: encoded,
      messageId: \`test-\${Date.now()}\`,
      publishTime: new Date().toISOString()
    }
  };
}

async function testHealthEndpoint() {
  try {
    console.log('🔍 Testing health endpoint...');
    const response = await axios.get(\`\${SERVER_URL}/health\`);
    console.log('✅ Health check passed:', response.data);
    return true;
  } catch (error) {
    console.error('❌ Health check failed:', error.message);
    return false;
  }
}

async function testPubSubEndpoint(userEmail) {
  try {
    console.log(\`🔍 Testing Pub/Sub endpoint with user: \${userEmail}\`);
    const testMessage = createTestMessage(userEmail);
    
    const response = await axios.post(\`\${SERVER_URL}/pubsub\`, testMessage, {
      headers: {
        'Content-Type': 'application/json'
      }
    });
    
    console.log('✅ Pub/Sub test passed:', response.data);
    return true;
  } catch (error) {
    console.error('❌ Pub/Sub test failed:', error.response?.data || error.message);
    return false;
  }
}

async function runTests() {
  const userEmail = process.argv[2];
  
  if (!userEmail) {
    console.error('Usage: node test.js <user-email>');
    process.exit(1);
  }
  
  console.log('🚀 Starting Gmail Pub/Sub Worker tests...');
  
  const healthOk = await testHealthEndpoint();
  if (!healthOk) {
    console.error('❌ Server is not healthy, aborting tests');
    process.exit(1);
  }
  
  const pubsubOk = await testPubSubEndpoint(userEmail);
  
  if (healthOk && pubsubOk) {
    console.log('\n🎉 All tests passed!');
  } else {
    console.log('\n❌ Some tests failed');
    process.exit(1);
  }
}

if (require.main === module) {
  runTests();
}

module.exports = {
  testHealthEndpoint,
  testPubSubEndpoint,
  createTestMessage
};
`;

  fs.writeFileSync('test.js', testScript);
  fs.chmodSync('test.js', '755');
  console.log('✅ Created test.js script');
}

function updatePackageJson() {
  const packagePath = 'package.json';
  let packageJson;
  
  try {
    packageJson = JSON.parse(fs.readFileSync(packagePath, 'utf8'));
  } catch (error) {
    console.error('❌ Could not read package.json');
    return;
  }
  
  // Add development scripts
  packageJson.scripts = {
    ...packageJson.scripts,
    "dev": "nodemon index.js",
    "test": "node test.js",
    "docker:build": "docker build -t gmail-pubsub-worker .",
    "docker:run": "docker run -p 8080:8080 --env-file .env gmail-pubsub-worker",
    "docker:compose": "docker-compose up --build"
  };
  
  // Add development dependencies
  packageJson.devDependencies = {
    ...packageJson.devDependencies,
    "axios": "^1.6.0"
  };
  
  fs.writeFileSync(packagePath, JSON.stringify(packageJson, null, 2));
  console.log('✅ Updated package.json with dev scripts');
}

async function main() {
  console.log('🚀 Gmail Pub/Sub Worker Development Setup');
  console.log('=========================================\n');
  
  try {
    // Check if .env already exists
    if (fs.existsSync('.env')) {
      const overwrite = await question('📁 .env file already exists. Overwrite? (y/N): ');
      if (overwrite.toLowerCase() !== 'y') {
        console.log('⏭️  Skipping .env creation');
      } else {
        await setupEnvironment();
      }
    } else {
      await setupEnvironment();
    }
    
    // Create additional development files
    createDockerComposeFile();
    createTestScript();
    updatePackageJson();
    
    // Install development dependencies
    console.log('\n📦 Installing development dependencies...');
    execCommand('npm install', 'Installing dependencies');
    
    console.log('\n🎉 Development setup complete!');
    console.log('\n📋 Next steps:');
    console.log('   1. Review the .env file and update any values');
    console.log('   2. Run: npm run dev');
    console.log('   3. Test: npm run test <user-email>');
    console.log('   4. Or use Docker: npm run docker:compose');
    
  } catch (error) {
    console.error('❌ Setup failed:', error.message);
    process.exit(1);
  } finally {
    rl.close();
  }
}

async function setupEnvironment() {
  console.log('🔧 Setting up environment variables...');
  
  const config = {};
  
  config.projectId = await question('Google Cloud Project ID: ');
  config.googleClientId = await question('Google OAuth Client ID: ');
  config.googleClientSecret = await question('Google OAuth Client Secret: ');
  config.nextAuthUrl = await question('NextAuth URL (e.g., https://your-app.vercel.app): ');
  config.supabaseUrl = await question('Supabase URL: ');
  config.supabaseKey = await question('Supabase Service Role Key: ');
  
  const generateKey = await question('Generate encryption key automatically? (Y/n): ');
  if (generateKey.toLowerCase() !== 'n') {
    config.encryptionKey = generateEncryptionKey();
    console.log('🔑 Generated encryption key');
  } else {
    config.encryptionKey = await question('Encryption Key (64 hex characters): ');
  }
  
  validateConfig(config);
  createEnvFile(config);
}

if (require.main === module) {
  main();
}

module.exports = {
  createTestMessage,
  generateEncryptionKey,
  validateConfig
};