apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gmail-pubsub-worker
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/cpu: "1000m"
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "100"
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 300
      containers:
      - image: gcr.io/insyte-467414/gmail-pubsub-worker:latest
        ports:
        - containerPort: 8080
        env: []
        volumeMounts:
        - mountPath: /etc/secrets
          name: gmail-worker-secrets-volume
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
      volumes:
      - name: gmail-worker-secrets-volume
        secret:
          secretName: gmail-worker-secrets